/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 modelDraco.gltf 
Author: Slava Z. (https://sketchfab.com/slava)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pony-cartoon-885d9f60b3a9429bb4077cfac5653cf9
Title: Pony Cartoon
*/

import { useGLTF } from '@react-three/drei';

export default function Model(props: any) {
  const { nodes, materials } = useGLTF('./model/modelDraco.gltf') as any;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.004}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.Body_SG1}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.Ground_SG}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.Interior_SG}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.Windows_SG}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/modelDraco.gltf');
