/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 modelDraco.gltf 
Author: _Sheep19 (https://sketchfab.com/s0h1o9b)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/2011-aston-martin-one-77-57d0b9062aab4e079fbb8d06bf39baf4
Title: 2011 Aston Martin One-77
*/

import { useGLTF } from '@react-three/drei';

export default function Model(props: any) {
  const { nodes, materials } = useGLTF('./model/modelDraco.gltf') as any;
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            geometry={nodes.body001_body_0.geometry}
            material={materials.body}
          />
          <mesh
            geometry={nodes.body001_aluminium_0.geometry}
            material={materials.aluminium}
          />
          <mesh
            geometry={nodes.body001_glass_0.geometry}
            material={materials.glass}
          />
          <mesh
            geometry={nodes.body001_black_0.geometry}
            material={materials.black}
          />
          <mesh
            geometry={nodes.body001_exhaust_0.geometry}
            material={materials.exhaust}
          />
          <mesh
            geometry={nodes.body001_logo_0.geometry}
            material={materials.logo}
          />
          <mesh
            geometry={nodes.body001_lights_0.geometry}
            material={materials.lights}
          />
          <mesh
            geometry={nodes.body001_mirror_0.geometry}
            material={materials.mirror}
          />
        </group>
        <group
          position={[-3.049, 8.456, -0.003]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={55.044}
        >
          <mesh
            geometry={nodes.body_lights_0.geometry}
            material={materials.lights}
          />
          <mesh
            geometry={nodes.body_black_0.geometry}
            material={materials.black}
          />
          <mesh
            geometry={nodes.body_lights001_0.geometry}
            material={materials['lights.001']}
          />
          <mesh
            geometry={nodes.body_lights002_0.geometry}
            material={materials['lights.002']}
          />
          <mesh
            geometry={nodes.body_lights003_0.geometry}
            material={materials['lights.003']}
          />
        </group>
        <group
          position={[2.72, 46.142, 126.665]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.007}
        >
          <mesh
            geometry={nodes.interior009_interior_0.geometry}
            material={materials.interior}
          />
          <mesh
            geometry={nodes.interior009_black_0.geometry}
            material={materials.black}
          />
          <mesh
            geometry={nodes.interior009_mirror_0.geometry}
            material={materials.mirror}
          />
          <mesh
            geometry={nodes.interior009_body_0.geometry}
            material={materials.body}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            geometry={nodes.tyre001_rims001_0.geometry}
            material={materials['rims.001']}
          />
          <mesh
            geometry={nodes.tyre001_rims_0.geometry}
            material={materials.rims}
          />
          <mesh
            geometry={nodes.tyre001_tyre_0.geometry}
            material={materials.tyre}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            geometry={nodes.tyre004_rims001_0.geometry}
            material={materials['rims.001']}
          />
          <mesh
            geometry={nodes.tyre004_rims_0.geometry}
            material={materials.rims}
          />
          <mesh
            geometry={nodes.tyre004_tyre_0.geometry}
            material={materials.tyre}
          />
        </group>
        <mesh
          geometry={nodes.brake_disc_brake_calipers_0.geometry}
          material={materials.brake_calipers}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.interior010_interior_0.geometry}
          material={materials.interior}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.windows_glass_0.geometry}
          material={materials.glass}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.interior002_interior_0.geometry}
          material={materials.interior}
          position={[5.031, 50.148, 34.193]}
          rotation={[-Math.PI / 2, -0.399, 0.419]}
          scale={[0.658, 4.144, 0.658]}
        />
        <mesh
          geometry={nodes.body005_lights004_0.geometry}
          material={materials['lights.004']}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.tyre002_brake_dics_0.geometry}
          material={materials.brake_dics}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.brake_disc001_brake_calipers_0.geometry}
          material={materials.brake_calipers}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.tyre003_brake_dics_0.geometry}
          material={materials.brake_dics}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
    </group>
  );
}

useGLTF.preload('./model/modelDraco.gltf');
