/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 modelDraco.gltf 
Author: TSB3DMODELS (https://sketchfab.com/TSB3DMODELS)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/2019-ford-ranger-raptor-civil-cities-skylines-c2d4113e6acd401cb1999f81bb318325
Title: 2019 Ford Ranger Raptor CIVIL (Cities Skylines)
*/

import { useGLTF } from '@react-three/drei';

export default function Model(props: any) {
  const { nodes, materials } = useGLTF('./model/modelDraco.gltf') as any;
  return (
    <group {...props} dispose={null}>
      <group position={[0.001, 12.782, -6.507]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Ford_Raptor_BASE__0.geometry}
          material={materials['Scene_-_Root']}
          position={[-0.001, -6.507, -12.782]}
        />
      </group>
    </group>
  );
}

useGLTF.preload('./model/modelDraco.gltf');
