/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 modelDraco.gltf 
Author: uzb_rx7 (https://sketchfab.com/uzbek_supra)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mazda-rx7-fce7ca5f3d7e44b1bf7e037cd8e3a89a
Title: Mazda rx7
*/

import { useGLTF } from '@react-three/drei';

export default function Model(props: any) {
  const { nodes, materials } = useGLTF('./model/modelDraco.gltf') as any;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials['1RX7_Calipers']}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials.RRBaseMatGlass}
        />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.RRBaseMatWM}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials.RRRX7_Blinker_L}
        />
        <mesh
          geometry={nodes.Object_14.geometry}
          material={materials.RRRX7_Blinker_R}
        />
        <mesh
          geometry={nodes.Object_16.geometry}
          material={materials.RRRX7_Body2}
        />
        <mesh
          geometry={nodes.Object_18.geometry}
          material={materials.RRRX7_BrakeLight}
        />
        <mesh
          geometry={nodes.Object_20.geometry}
          material={materials.RRRX7_BrakeLight2}
        />
        <mesh
          geometry={nodes.Object_22.geometry}
          material={materials.RRRX7_FogLights}
        />
        <mesh
          geometry={nodes.Object_24.geometry}
          material={materials.RRRX7_ReverseLights}
        />
        <mesh
          geometry={nodes.Object_26.geometry}
          material={materials['1RX7_Rims']}
        />
        <mesh
          geometry={nodes.Object_28.geometry}
          material={materials.RRBaseMatGeneral}
        />
        <mesh
          geometry={nodes.Object_30.geometry}
          material={materials.RRRX7_Body}
        />
        <mesh
          geometry={nodes.Object_32.geometry}
          material={materials.RRRX7_HeadLights}
        />
      </group>
    </group>
  );
}

useGLTF.preload('./model/modelDraco.gltf');
